#!/bin/bash
WORKDIR=$1
Zeit=`date '+%H%M%S'`
datum=`date '+%Y%m%d'`
echo "Schalte Heizung ein"

echo io set port 2 00 02 | nc -w 2 192.168.2.24 2701
RC=$?

if [ $RC -eq 0 ]; then
        sql="insert into ausEin_Historie values(null,$datum,$Zeit,'Heizung',1,0)"
        mysql -u aquarium -paquarium -h $dbhost -D aquarium -e "$sql" >/dev/null 2>&1
fi
exit $RC
