#!/bin/bash
WORKDIR=$1
Zeit=`date '+%H:%M:%S'`
datum=`date '+%Y-%m-%d'`
echo "Schalte Luefter ein"
#Dose 5
echo io set port 2 00 10 | nc -w 2 192.168.2.24 2701
RC=$?

if [ $RC -eq 0 ]; then
        sql="insert into ausEin_Historie values(default,$datum,$Zeit,'Luefter',1,0)"                                                                                                            
        #mysql -u aquarium -paquarium -h $dbhost -D aquarium -e "$sql"      >/dev/null 2>&1  
        export PGPASSWORD=aquarium
        psql -h  127.0.0.1  -U aquarium -d aquarium -p 26257 -c "$sql"                                                                                                               
fi
exit $RC
